version: '3.8'

services:
  mariadb:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    container_name: mariadb-container
    ports:
      - "3306:3306"
    networks:
      - my-network

  springboot:
    build:
      context: .
      dockerfile: ./docker/springboot/Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mariadb

networks:
  my-network:
    driver: bridge
